# the keys under which relevant properties are stored in the JobNimbus API
KEY_JNID = "jnid"
KEY_SALES_REP = "sales_rep_name"
KEY_INSURANCE_CHECKBOX = "Insurance Job?"
KEY_INSURANCE_COMPANY_NAME = "Insurance Company"
KEY_INSURANCE_CLAIM_NUMBER = "Claim #"
KEY_JOB_NUMBER = "number"
KEY_JOB_NAME = "name"
KEY_APPOINTMENT_DATE = "Sales Appt Date"
KEY_CONTINGENCY_DATE = "Signed Contingency Date"
KEY_CONTRACT_DATE = "Signed Contract Date"
KEY_INSTALL_DATE = "Install Date"
KEY_LOSS_DATE = "Job Lost Date (Lost Status)"
KEY_AMOUNT_RECEIVABLE = "approved_invoice_due"
KEY_STATUS_NAME = "status_name"
KEY_STATUS_MOD_TIME = "date_status_change"